### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by harrisoncattell** [schorschii/LAPS4LINUX#13]
When running the code from source without modification, I am getting a syntax error;

 File "laps-runner.py", line 107
    res = resolver.resolve(qname=f'_ldap._tcp'+searchDomain, rdtype=rdatatype.SRV, lifetime=10, search=True)
                                             ^
SyntaxError: invalid syntax

**Comment by schorschii** [comment]
This is not a bug. If you need assistance in deploying LAPS4LINUX in your corporate environment, please accept my offer for commercial support.
