### ISSUE TITLE
Laps-runner error

### ISSUE THREAD

**Issue by Flooxou** [schorschii/LAPS4LINUX#15]
Hi, I try to run "laps-runner.py" and I get the error "exit code 1" like in the troubleshooting part. So I do the following commands but it's not very explicit and I don't understand why it doesn't work. 

![kinit_LI](https://github.com/schorschii/LAPS4LINUX/assets/78875692/92aceee4-ba21-43c9-88f9-4d4576ac8654)
![error klist_LI](https://github.com/schorschii/LAPS4LINUX/assets/78875692/af89900f-a848-4e1a-aca5-9ef615fc316d)

**Comment by Flooxou** [comment]
I managed to unblock myself, I had to run in sudo and my hostname was the wrong one, the right one was "PCTEST".

**Comment by schorschii** [comment]
Don't forget to give this repo a star if you like it :)
