### ISSUE TITLE
Login test / Wrong password

### ISSUE THREAD

**Issue by Flooxou** [schorschii/LAPS4LINUX#17]
Hi,

When I try to connect to my root account with the password given by LAPS UI on the Windows Server it does not work. However when I change the expiration date a new password is provided by laps-runner. I don't understand where the problem comes from. Can you help me?

Thank you.
![Laps-runner_LI](https://github.com/schorschii/LAPS4LINUX/assets/78875692/90e8d8e4-e46d-4dd5-a236-2d458ba3f356)

**Comment by schorschii** [comment]
"Try to connect" means via SSH? Is password authentication enabled for root via SSH? It's disabled by default in many distros.

**Comment by Flooxou** [comment]
No, directly from terminal "su root"

**Comment by schorschii** [comment]
What does `laps-runner -f` show in terminal?

**Comment by Flooxou** [comment]
I don't know why, but it works now after making the order

**Comment by schorschii** [comment]
Please try again by setting the expiration date in the past and execute `laps-runner` (without `-f`).

**Comment by Flooxou** [comment]
Should I disable the cron that runs the "laps-runner --config /etc/laps-runner.json" command?

**Comment by schorschii** [comment]
Yes, please disable it for testing purposes.

**Comment by Flooxou** [comment]
After doing the command and disabling the cron, it did change the password and I can log in now. I don't know why it didn't work before
