### ISSUE TITLE
Usermod call depends on PATH, which CRON may break

### ISSUE THREAD

**Issue by nswright** [schorschii/LAPS4LINUX#18]
Currently, the call to usermod to update the password locally depends on usermod being in the PATH. Since cron does not run under a shell, it typically has a very minimal PATH by default, such as "/usr/bin:/bin". If a user naively runs the script using cron after verifying it works in their shell, this would cause the password to be updated in the directory and not locally, locking the user out of the account. 

At the very least, this failure state should be explicitly called out in the documentation. Currently, the documentation includes a shebang to use the sh shell in the example crontab, but it is unclear why it is included. It also may be worth it to verify usermod is in the PATH before updating the password in the directory, which would prevent this failure state from happening in the first place.

**Comment by schorschii** [comment]
I agree, there should be a check for usermod before changing the password in the LDAP directory and a bit more documentation. My test environments are Debian and Ubuntu, where /usr/sbin (for /usr/sbin/usermod) is in crontab PATH. Which distro are you using?
