### ISSUE TITLE
Searching in Forests

### ISSUE THREAD

**Issue by anykeypress** [schorschii/LAPS4LINUX#2]
Hi, super application,works as required, with the exception that when searching for an existing computer object it does not take forests into consideration... for example:

boohaa.org Top Level
de.boohaa.org Forest

pc1.boohhaa.org is found
pc2.de.boohaa.org ist not found

Or am I doing something wrong?

**Comment by schorschii** [comment]
Please test it with the new version 1.4.1. I added support for modifying the password expiry date when using the GC in this version. All details how the configuration file has to be adjusted for the new version ist documented in the [README](https://github.com/schorschii/LAPS4LINUX/tree/v1.4.1#domain-forest-searches).
Kind regards
Georg

**Comment by anykeypress** [comment]
Hi George,
I've tried the new version, however I get the following error:
![error](https://user-images.githubusercontent.com/16607225/140938850-8afed1e7-3f8e-4fe1-b8cc-c55dd6fec919.png)

I initially installed the laps-runner deb. Used the "Old" GUI to test, ok. Ran the laps-runner (using the -f switch) worked ok (my machine is in the top lovel dom). Then installed the laps-client deb. Got the error shown in the screenshot (of course after editing the settings.). To be on the safe side, I deleted my old settings file and started the GUI to recreate a settings file, all to no avail...

Cheers
Phil

**Comment by schorschii** [comment]
Thanks for your feedback. I found an issue with Kerberos authentication in combination with the global catalog search, please test it again with [v1.4.3](https://github.com/schorschii/LAPS4LINUX/releases/tag/v1.4.3).

**Comment by anykeypress** [comment]
Hi George,
Followed the same procedure as I did on updating to 1.4.2. Works as expected!
Thanks for your continued work and the fix!

Cheers
Phil

**Comment by schorschii** [comment]
Great, thanks for testing!
