### ISSUE TITLE
Is it working with FreeIPA/OpenLDAP ?

### ISSUE THREAD

**Issue by BornTKill** [schorschii/LAPS4LINUX#28]
Hello,

I am wondering if i can use this project with LDAP not from Microsoft ?

Regards.

**Comment by schorschii** [comment]
Yes, you can. LAPS4LINUX uses standard LDAP protocol features for the base functionality. Only the optional encryption, introduced by MS in 2023 with the new Native LAPS, relies on proprietary RPC calls which are specific to MS Active Directory.

You may need to adjust your LDAP schema to add attributes to your computer objects where to store the password and expiration date. My OpenLDAP knowledge is limited, so unfortunately, I currently can't help you with that. However, I'm interested in documenting how to use LAPS4LINUX with OpenLDAP. If you dig deeper into this, I'd appreciate if you share your perceptions.

**Comment by BornTKill** [comment]
Ok i Will try and let you know :)

**Comment by schorschii** [comment]
I was able to gain some OpenLDAP experience through another project. I just made some changes to make LAPS4LINUX fully OpenLDAP compatible and added OpenLDAP setup instructions [here](https://github.com/schorschii/LAPS4LINUX/blob/master/docs/OpenLDAP.md). You may give it a try. To be honest, especially the Kerberos setup is not trivial, so the [idea of ​​implementing a LAPS alternative in OCO](https://github.com/schorschii/OCO-Server/issues/42) seems to be worth the effort.
