### ISSUE TITLE
Cannot build working deb version of laps-runner with build script

### ISSUE THREAD

**Issue by fraunhofer-ipm-itk** [schorschii/LAPS4LINUX#29]
Hi,

I think I've found a bug in the build script for deb packages, specifically the laps4linux-runner section.
## The Problem
After building the laps4linux-runner debian package, the installation errors out with the following message:
```bash
 × python setup.py egg_info did not run successfully.
					  │ exit code: 1
					  ╰─> [6 lines of output]
					      Traceback (most recent call last):
					        File "<string>", line 2, in <module>
					        File "<pip-setuptools-caller>", line 34, in <module>
					        File "/usr/share/laps4linux-runner/setup.py", line 8, in <module>
					          with open(os.path.join(here, 'README.md'), encoding='utf-8') as f:
					      FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/laps4linux-runner/README.md'
					      [end of output]
```
## Steps to reproduce
(tested on WSL Ubuntu 22.04.4)
1. Clone the repository and change into `LAPS4LINUX/installer/deb/`
2. run `build.sh`
3. install the laps4linux-runner.deb with `sudo apt install ./laps4linux-runner.deb`

## Possible fix
The file `/usr/share/laps4linux-runner/README.md` never makes it into the package.
This is because the file isn't copied into the runner build directory, only into the client build directory.
Copying the following line from earlier in the script into the runner-section* seems to fix the issue:
```bash
# copy files in place
sudo install -D -m 644 ../../README.md                         -t $BUILDDIR/$INSTALLDIR
```
*Edit: I mean the section starting with this code
```bash
# build runner .deb package
INSTALLDIR=/usr/share/laps4linux-runner
BUILDDIR=laps4linux-runner
```

Thanks and Kind regards,
Simon

**Comment by schorschii** [comment]
Thanks for reporting!
