### ISSUE TITLE
Missing LAPS4LINUX Packages in Sponsor tier

### ISSUE THREAD

**Issue by dknz7** [schorschii/LAPS4LINUX#36]
Hi schorschii,

I have sponsored to gain access to the RPMs for LAPS4LINUX but the repository is currently empty.

Would you mind please posting the latest RPM file for the client and runner for CentOS? That's all I am really after to re-host the RPMs internally

Cheers,
dknz7

**Comment by dknz7** [comment]
Found the spot, I am silly xD

**Comment by schorschii** [comment]
OK, thanks for supporting my work!
