### ISSUE TITLE
Inconsistency between manual install instructions and .deb postinst script

### ISSUE THREAD

**Issue by rkerr** [schorschii/LAPS4LINUX#37]
I noticed that whilst the manual install instructions say to use the --system-site-packages option when creating the venv the postinst script that's part of the debian package doesn't do so? Should the postinst script also use --system-site-packages ?

**Comment by schorschii** [comment]
Yes, this reduces the amount of libraries which need to be installed in the venv when they are already installed in the system via apt. Added in b6a6f8fabe3752b3021e78899092635c7e181515.
