### ISSUE TITLE
Debian package build script

### ISSUE THREAD

**Issue by schorschii** [schorschii/LAPS4LINUX#9]
Similar to RPM build script

**Comment by hwittenborn** [comment]
Would [makedeb](https://makedeb.org) be of any interest? It would do the same thing as a Debian build script, but would get everything working through a standardized file format, and would allow for integration into other things in an easier way.

You could also upload it to the [makedeb Package Repository](https://mpr.makedeb.org) after, which would allow you to more easily reach other users.

---
P.s. makedeb and the MPR are personal projects of mine.
